version: "3.9"

services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: $POSTGRES_USER 
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports: 
      - '5432:5432'

  gagamboy:
    build:
      context: .
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env